name: Convert Markdown to HTML

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: create html folder
        run: mkdir html

      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            README.md
            --metadata pagetitle="「一个人的书房」捐赠列表"
            -s
            -o "./html/index.html"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          cname: i.shufang.org

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami; cd ${{ secrets.WEBSITE_ABS_PATH }}; git pull
